version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    working_dir: /app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx/
      - ./ssl:/etc/nginx/ssl
  php-fpm:
    image: php:fpm
    container_name: php_fpm
    working_dir: /app
    volumes:
      - ./html:/app
    
