version: '3.7'

services:
  nginx:
    build: ./
    container_name: nginx
    working_dir: /usr/local/nginx/html
#    tty: true 
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx/
